#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

mknod -m 666 /dev/ttyS0 c 4 64
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0 
mknod -m 444 /dev/random c 1 8
mknod -m 444 /dev/urandom c 1 9


echo -e "\n-----Hello world!-----\nType \"poweroff -f\" for a clean system shutdown"

setsid  cttyhack sh
exec /bin/sh
